name: Update ODEPA Data

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js

      - name: Commit JSON
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/precios.json
          git commit -m "update precios" || echo "no changes"
          git push
